# Makefile

# Compilador
CC = g++

# Opciones de compilación
CFLAGS = -lglut -lGL -lGLU -w

# Nombre del ejecutable
TARGET = ejemplo

# Archivos objeto
OBJS = main.o chess.o ejemplo.o

# Regla por defecto
all: $(TARGET)

# Regla para crear el ejecutable
$(TARGET): $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) -o $(TARGET)

# Regla para compilar cada archivo objeto
%.o: %.c
	$(CC) -c $<

# Regla para limpiar archivos generados
clean:
	rm -f $(OBJS) $(TARGET)

